### ISSUE TITLE
Add support for --require cli argument

### ISSUE THREAD

**Issue by zcrumbo** [rei/vunit#16]
Can we whitelist `--require` as an accepted cli argument so users can configure mocha with additional global setup files?

**Desired functionality**
Be able to add the following script to the `package.json` file and have it pull in a config file for mocha
```
"scripts" : {
  "test": "vunit --spec=./test/**/*.spec.js --require=./test/setup.js" 
}
```
**Current functionality**
Adding the script returns `Invalid option given: require`

**Comment by peripateticus** [comment]
Yeah, that looks doable, currently we're doing an internal `--require setup.js` but it'll be straightforward to expose this on the API.

**Comment by zcrumbo** [comment]
I put together a basic PR for this - we're finding we need to mock out some globals and I'd rather do it via a local module than an external library/dependancy
